version: '3.5'
services:
  mysql:
    build: './IaC/mysql/'
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - db_data:/var/lib/mysql
volumes:
    db_data: {}